// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9-2dDUN12-aWEzGwJhbhrq5m45XbGCiQ',
    appId: '1:462436298694:web:94f0f9f0984421e4b1ccc7',
    messagingSenderId: '462436298694',
    projectId: 'west-elbalad',
    authDomain: 'west-elbalad.firebaseapp.com',
    storageBucket: 'west-elbalad.appspot.com',
    measurementId: 'G-F0JMMBRE5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2r3OLbshKPjY7c1iTry1A3IPM44T85OA',
    appId: '1:462436298694:android:a477def5b044efcdb1ccc7',
    messagingSenderId: '462436298694',
    projectId: 'west-elbalad',
    storageBucket: 'west-elbalad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf0_FuXLaZwjY1C8KCua83tVgcGQ61x6w',
    appId: '1:462436298694:ios:49197b6509a4730cb1ccc7',
    messagingSenderId: '462436298694',
    projectId: 'west-elbalad',
    storageBucket: 'west-elbalad.appspot.com',
    iosBundleId: 'com.example.westElbalad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf0_FuXLaZwjY1C8KCua83tVgcGQ61x6w',
    appId: '1:462436298694:ios:49197b6509a4730cb1ccc7',
    messagingSenderId: '462436298694',
    projectId: 'west-elbalad',
    storageBucket: 'west-elbalad.appspot.com',
    iosBundleId: 'com.example.westElbalad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9-2dDUN12-aWEzGwJhbhrq5m45XbGCiQ',
    appId: '1:462436298694:web:c97f2d88c4a16e02b1ccc7',
    messagingSenderId: '462436298694',
    projectId: 'west-elbalad',
    authDomain: 'west-elbalad.firebaseapp.com',
    storageBucket: 'west-elbalad.appspot.com',
    measurementId: 'G-W2Y5ZTZLRZ',
  );
}
